version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/psql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/psql/data/

volumes:
  db:
